name: CI
on: [push, pull_request]
jobs:
    ubuntu-latest:
        runs-on: ubuntu-latest
        steps:
            - name: Installing V
              run: cd ~; git clone https://github.com/vlang/v.git; cd v; make CC=clang; sudo ./v symlink
            - uses: actions/checkout@v1
            - name: Running Test
              env:
                  VFLAGS: -show_c_cmd -cg
              run: v version; v test .
